# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: No Titles
description: ...except that one.
baseurl: /blog # the subpath of your site, e.g. /blog
url: http://www.grchen.com # the base hostname & protocol for your site http://www.example.com
google_analytics: 'UA-80010838-1'

# Build settings
markdown: kramdown

permalink: '/:month-:day-:year-:title.html'

gems: [jekyll-paginate]

paginate: 10
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts